---
name: Updates the Jenkins repositories

on:
  push:
    branches:
      - main
    paths:
      - 'repos.csv'
jobs:
  update-ingest:
    runs-on: ubuntu-latest
    steps:
      - name: detect org
        run: |
         echo "ADDED_ORG=$(echo "${{ github.event.head_commit.message }}" | sed 's/\[Auto\] The \(.*\) GitHub organization is added$/\1/')" >> $GITHUB_ENV
      - name: update org
        if: ${{ env.ADDED_ORG != github.event.head_commit.message }}
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: jenkins.yaml
          repo: moderneinc/moderne-cli
          inputs: '{ "prefix": {{ env.ADDED_ORG }}, "csvUrl": "https://raw.githubusercontent.com/moderneinc/jenkins-ingest/main/repos.csv", "downloadCLI": false, "folder": "cli-ingest" }'
      - name: update the entire list
        if: ${{ env.ADDED_ORG == github.event.head_commit.message }}
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: jenkins.yaml
          repo: moderneinc/moderne-cli
          inputs: '{  "csvUrl": "https://raw.githubusercontent.com/moderneinc/jenkins-ingest/main/repos.csv", "downloadCLI": false, "folder": "cli-ingest" }'
     
